#!/usr/bin/env node
// Generated by scripts/generate-runtime-dist.mjs. Do not edit directly.


// scripts/xgc-update.mjs
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
var DEFAULT_REPO = "Juhwa-Lee1023/x-for-github-copilot";
var PACKAGE_NAME = "x-for-github-copilot";
var CHECK_INTERVAL_MS = 24 * 60 * 60 * 1e3;
var MAX_RELEASE_BYTES = 25 * 1024 * 1024;
var FETCH_TIMEOUT_MS = 6e4;
function parseSemver(input) {
  const match = String(input).trim().match(/^v?(\d+)\.(\d+)\.(\d+)$/);
  if (!match) return null;
  return { major: Number(match[1]), minor: Number(match[2]), patch: Number(match[3]) };
}
function normalizeReleaseRepo(input) {
  const value = String(input ?? "").trim();
  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(value)) {
    throw new Error(`Invalid release repository: ${value}`);
  }
  return value;
}
function isSafeTarPath(entryPath) {
  if (!entryPath || entryPath.includes("\0") || entryPath.startsWith("/") || /^[A-Za-z]:[\\/]/.test(entryPath)) {
    return false;
  }
  const normalized = path.posix.normalize(entryPath.replace(/\\/g, "/"));
  return normalized !== "." && normalized !== ".." && !normalized.startsWith("../");
}
function validateTarballEntries(archivePath) {
  const names = run("tar", ["-tzf", archivePath]).stdout.split(/\r?\n/).filter(Boolean);
  if (names.length === 0) {
    throw new Error("Release tarball is empty.");
  }
  for (const entryName of names) {
    if (!isSafeTarPath(entryName)) {
      throw new Error(`Unsafe release tarball path: ${entryName}`);
    }
  }
  const verbose = run("tar", ["-tvzf", archivePath]).stdout.split(/\r?\n/).filter(Boolean);
  for (const line of verbose) {
    const type = line[0];
    if (type !== "-" && type !== "d") {
      throw new Error(`Release tarball contains unsupported link or special entry: ${line}`);
    }
  }
}
function sha256File(filePath) {
  const hash = createHash("sha256");
  hash.update(fs.readFileSync(filePath));
  return hash.digest("hex");
}
async function fetchJson(url, description) {
  const response = await fetch(url, {
    headers: {
      "user-agent": "xgc-update"
    }
  });
  if (!response.ok) {
    throw new Error(`Unable to fetch ${description}: ${response.status} ${response.statusText}`);
  }
  return response.json();
}
async function downloadFile(url, outputPath, description) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const response = await fetch(url, {
      headers: {
        "user-agent": "xgc-update"
      },
      signal: controller.signal
    });
    if (!response.ok) {
      throw new Error(`Unable to download ${description}: ${response.status} ${response.statusText}`);
    }
    const contentLength = Number(response.headers.get("content-length") ?? "0");
    if (Number.isFinite(contentLength) && contentLength > MAX_RELEASE_BYTES) {
      throw new Error(`${description} is too large: ${contentLength} bytes`);
    }
    const reader = response.body?.getReader();
    if (!reader) {
      throw new Error(`Unable to stream ${description}`);
    }
    const chunks = [];
    let total = 0;
    while (true) {
      const { done, value } = await reader.read();
      if (done) {
        break;
      }
      total += value.byteLength;
      if (total > MAX_RELEASE_BYTES) {
        throw new Error(`${description} exceeded max size ${MAX_RELEASE_BYTES} bytes`);
      }
      chunks.push(Buffer.from(value));
    }
    fs.writeFileSync(outputPath, Buffer.concat(chunks));
  } finally {
    clearTimeout(timeout);
  }
}
function compareSemver(left, right) {
  if (left.major !== right.major) return left.major - right.major;
  if (left.minor !== right.minor) return left.minor - right.minor;
  return left.patch - right.patch;
}
function deriveDefaultUpdateTrack(version) {
  const parsed = typeof version === "string" ? parseSemver(version) : version;
  if (!parsed) throw new Error(`Invalid semantic version: ${version}`);
  return parsed.major === 0 ? `0.${parsed.minor}` : String(parsed.major);
}
function deriveDefaultUpdatePolicy(version) {
  const parsed = typeof version === "string" ? parseSemver(version) : version;
  if (!parsed) throw new Error(`Invalid semantic version: ${version}`);
  return parsed.major === 0 ? "patch-within-track" : "minor-within-major";
}
function normalizeAutoUpdateMode(value) {
  return value === "off" || value === "check" || value === "apply" ? value : "check";
}
function isCompatibleUpdate({ current, candidate, track, policy }) {
  const currentVersion = typeof current === "string" ? parseSemver(current) : current;
  const candidateVersion = typeof candidate === "string" ? parseSemver(candidate) : candidate;
  if (!currentVersion || !candidateVersion) return false;
  if (compareSemver(candidateVersion, currentVersion) <= 0) return false;
  const effectivePolicy = policy || deriveDefaultUpdatePolicy(currentVersion);
  const effectiveTrack = track || deriveDefaultUpdateTrack(currentVersion);
  if (effectivePolicy === "patch-within-track") {
    return effectiveTrack === `${candidateVersion.major}.${candidateVersion.minor}`;
  }
  return effectiveTrack === String(candidateVersion.major);
}
function parseArgs(argv) {
  const args = {
    homeDir: os.homedir(),
    configHome: null,
    checkOnly: false,
    ifDue: false,
    quiet: false,
    repo: null,
    autoUpdateMode: null
  };
  for (let index = 0; index < argv.length; index += 1) {
    const current = argv[index];
    if (current === "--check") {
      args.checkOnly = true;
    } else if (current === "--if-due") {
      args.ifDue = true;
    } else if (current === "--quiet") {
      args.quiet = true;
    } else if (current === "--home-dir" && argv[index + 1]) {
      args.homeDir = path.resolve(argv[index + 1]);
      index += 1;
    } else if (current === "--config-home" && argv[index + 1]) {
      args.configHome = path.resolve(argv[index + 1]);
      index += 1;
    } else if (current === "--repo" && argv[index + 1]) {
      args.repo = argv[index + 1];
      index += 1;
    } else if (current === "--auto-update-mode" && argv[index + 1]) {
      args.autoUpdateMode = normalizeAutoUpdateMode(argv[index + 1]);
      index += 1;
    }
  }
  return args;
}
function resolvePaths(args) {
  const configHome = args.configHome ?? path.join(args.homeDir, ".config", "xgc");
  return {
    configHome,
    installStatePath: path.join(configHome, "install-state.json"),
    shellEnvPath: path.join(configHome, "profile.env"),
    updaterPath: path.join(configHome, "xgc-update.mjs"),
    runtimeHome: path.join(args.homeDir, ".local", "share", "xgc"),
    runtimeReleasesHome: path.join(args.homeDir, ".local", "share", "xgc", "releases"),
    runtimeCurrentPath: path.join(args.homeDir, ".local", "share", "xgc", "current")
  };
}
function readJsonIfExists(filePath) {
  if (!fs.existsSync(filePath)) {
    return null;
  }
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}
function writeJson(filePath, payload) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(payload, null, 2)}
`);
}
async function fetchReleaseIndex(repo) {
  const payload = await fetchJson(`https://api.github.com/repos/${repo}/releases?per_page=100`, `releases for ${repo}`);
  if (!Array.isArray(payload)) {
    throw new Error(`Unexpected releases payload for ${repo}`);
  }
  return payload.filter((entry) => !entry.draft && !entry.prerelease).map((entry) => {
    const version = String(entry.tag_name ?? "").replace(/^v/, "");
    const expectedAssetName = `${PACKAGE_NAME}-${version}.tgz`;
    const assets = Array.isArray(entry.assets) ? entry.assets : [];
    const tarballAsset = assets.find((asset) => asset?.name === expectedAssetName && asset?.browser_download_url);
    const manifestAsset = assets.find((asset) => asset?.name === "release-manifest.json" && asset?.browser_download_url);
    return {
      version,
      tag: String(entry.tag_name ?? ""),
      tarballUrl: tarballAsset?.browser_download_url ?? null,
      manifestUrl: manifestAsset?.browser_download_url ?? null,
      publishedAt: entry.published_at ?? null
    };
  }).filter((entry) => parseSemver(entry.version) && entry.tag && entry.tarballUrl);
}
function selectLatestCompatibleRelease(releases, installState) {
  const compatibles = releases.filter(
    (entry) => isCompatibleUpdate({
      current: installState.version,
      candidate: entry.version,
      track: installState.updateTrack,
      policy: installState.updatePolicy
    })
  ).sort((left, right) => compareSemver(parseSemver(right.version), parseSemver(left.version)));
  return compatibles[0] ?? null;
}
function shouldSkipDueCheck(installState) {
  const lastCheck = installState.lastUpdateCheckAt ? Date.parse(installState.lastUpdateCheckAt) : NaN;
  return Number.isFinite(lastCheck) && Date.now() - lastCheck < CHECK_INTERVAL_MS;
}
function withCheckMetadata(installState, extra = {}) {
  return {
    ...installState,
    ...extra,
    lastUpdateCheckAt: (/* @__PURE__ */ new Date()).toISOString()
  };
}
function readInstallState(paths) {
  const installState = readJsonIfExists(paths.installStatePath);
  if (!installState) {
    throw new Error(
      `Missing install state at ${paths.installStatePath}. Run npx x-for-github-copilot install first.`
    );
  }
  const version = installState.version;
  if (!parseSemver(version)) {
    throw new Error(`Install state is missing a valid version: ${paths.installStatePath}`);
  }
  return {
    ...installState,
    releaseRepo: installState.releaseRepo || DEFAULT_REPO,
    updateChannel: installState.updateChannel || "stable",
    updateTrack: installState.updateTrack || deriveDefaultUpdateTrack(version),
    updatePolicy: installState.updatePolicy || deriveDefaultUpdatePolicy(version),
    autoUpdateMode: normalizeAutoUpdateMode(installState.autoUpdateMode)
  };
}
function print(message, quiet) {
  if (!quiet) {
    console.log(message);
  }
}
function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    stdio: "pipe",
    ...options
  });
  if (result.status !== 0) {
    throw new Error(
      [`${command} ${args.join(" ")}`, result.stdout?.trim(), result.stderr?.trim()].filter(Boolean).join("\n")
    );
  }
  return result;
}
async function expectedSha256ForRelease(release) {
  if (!release.manifestUrl) {
    return null;
  }
  const manifest = await fetchJson(release.manifestUrl, `release manifest for ${release.tag}`);
  const checksum = manifest?.npmPackageSha256 ?? manifest?.npmPackage?.sha256 ?? null;
  if (typeof checksum !== "string" || !/^[a-f0-9]{64}$/i.test(checksum)) {
    return null;
  }
  return checksum.toLowerCase();
}
function locateAndValidateExtractedPackage(tempRoot, expectedVersion) {
  const extractedDir = path.join(tempRoot, "package");
  if (!fs.existsSync(path.join(extractedDir, "package.json"))) {
    throw new Error(`Release tarball must extract to a package/ directory with package.json.`);
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(extractedDir, "package.json"), "utf8"));
  if (pkg.name !== PACKAGE_NAME || pkg.version !== expectedVersion) {
    throw new Error(`Release package identity mismatch: expected ${PACKAGE_NAME}@${expectedVersion}`);
  }
  for (const requiredFile of [
    "bin/xgc.mjs",
    "runtime-dist/materialize-global-xgc.mjs",
    "runtime-dist/validate-global-xgc.mjs",
    "runtime-dist/xgc-update.mjs"
  ]) {
    if (!fs.existsSync(path.join(extractedDir, requiredFile))) {
      throw new Error(`Release package is missing required runtime file: ${requiredFile}`);
    }
  }
  return extractedDir;
}
function updateInstallState(paths, current, patch) {
  writeJson(paths.installStatePath, { ...current, ...patch });
}
async function main() {
  const args = parseArgs(process.argv.slice(2));
  const paths = resolvePaths(args);
  const installState = readInstallState(paths);
  const repo = normalizeReleaseRepo(args.repo || installState.releaseRepo || DEFAULT_REPO);
  const backgroundMode = args.autoUpdateMode || installState.autoUpdateMode || "check";
  const effectiveMode = args.checkOnly ? "check" : args.ifDue ? backgroundMode : "apply";
  if (args.ifDue && shouldSkipDueCheck(installState)) {
    process.exit(0);
  }
  const releases = await fetchReleaseIndex(repo);
  const latestCompatible = selectLatestCompatibleRelease(releases, installState);
  const currentVersion = installState.version;
  if (!latestCompatible) {
    updateInstallState(paths, installState, withCheckMetadata(installState, {
      releaseRepo: repo,
      lastUpdateStatus: "up_to_date",
      lastKnownAvailableVersion: currentVersion
    }));
    print(`xgc update: ${currentVersion} is already the latest compatible release on track ${installState.updateTrack}.`, args.quiet);
    return;
  }
  if (effectiveMode === "check") {
    updateInstallState(paths, installState, withCheckMetadata(installState, {
      releaseRepo: repo,
      lastUpdateStatus: "update_available",
      lastKnownAvailableVersion: latestCompatible.version
    }));
    print(
      `xgc update: ${currentVersion} -> ${latestCompatible.version} is available on track ${installState.updateTrack} (${installState.updatePolicy}). Run xgc update or xgc_update to apply it.`,
      args.quiet
    );
    return;
  }
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), "xgc-update-"));
  try {
    const archivePath = path.join(tempRoot, "release.tgz");
    await downloadFile(latestCompatible.tarballUrl, archivePath, "release tarball");
    const expectedSha256 = await expectedSha256ForRelease(latestCompatible);
    if (!expectedSha256) {
      throw new Error(`Release manifest checksum is required before applying ${latestCompatible.tag}`);
    }
    const actualSha256 = sha256File(archivePath);
    if (actualSha256 !== expectedSha256) {
      throw new Error(`Release tarball checksum mismatch for ${latestCompatible.tag}`);
    }
    validateTarballEntries(archivePath);
    run("tar", ["-xzf", archivePath, "-C", tempRoot]);
    const extractedDir = locateAndValidateExtractedPackage(tempRoot, latestCompatible.version);
    print(`xgc update: applying ${currentVersion} -> ${latestCompatible.version}`, args.quiet);
    run(
      process.execPath,
      [
        path.join(extractedDir, "bin", "xgc.mjs"),
        "install",
        "--home-dir",
        args.homeDir,
        "--permission-mode",
        installState.permissionMode || "ask",
        "--reasoning-effort",
        installState.reasoningEffort || "xhigh",
        "--reasoning-effort-cap",
        installState.reasoningEffortCap || "high",
        "--no-write-shell-profile",
        "--release-repo",
        repo,
        "--release-tag",
        latestCompatible.tag,
        "--update-track",
        installState.updateTrack,
        "--update-channel",
        installState.updateChannel,
        "--auto-update-mode",
        backgroundMode
      ],
      {
        cwd: extractedDir,
        env: {
          ...process.env,
          XGC_SKIP_SELF_DISPATCH: "1"
        }
      }
    );
  } finally {
    fs.rmSync(tempRoot, { recursive: true, force: true });
  }
  const refreshed = readInstallState(paths);
  updateInstallState(paths, refreshed, {
    releaseRepo: repo,
    releaseTag: latestCompatible.tag,
    lastUpdateCheckAt: (/* @__PURE__ */ new Date()).toISOString(),
    lastUpdateStatus: "updated",
    lastKnownAvailableVersion: latestCompatible.version,
    lastUpdatedFromVersion: currentVersion,
    lastUpdateAppliedAt: (/* @__PURE__ */ new Date()).toISOString()
  });
  print(`xgc update: now on ${latestCompatible.version}`, args.quiet);
}
main().catch((error) => {
  const args = parseArgs(process.argv.slice(2));
  const paths = resolvePaths(args);
  try {
    const installState = readInstallState(paths);
    updateInstallState(paths, installState, withCheckMetadata(installState, {
      lastUpdateStatus: "failed"
    }));
  } catch {
  }
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
