#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${XGC_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
YES=0
SKIP_INSTALL=0
SKIP_PROFILE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes|-y)
      YES=1
      shift
      ;;
    --skip-install)
      SKIP_INSTALL=1
      shift
      ;;
    --skip-profile)
      SKIP_PROFILE=1
      shift
      ;;
    --repo-root)
      REPO_ROOT="$(cd "$2" && pwd)"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

mkdir -p "$REPO_ROOT/.xgc/bootstrap" "$REPO_ROOT/.tmp"
if [[ $SKIP_INSTALL -eq 0 ]]; then
  if [[ -d "$REPO_ROOT/node_modules" ]]; then
    echo "Skipping repo npm install because node_modules is already present."
  else
    npm install --prefix "$REPO_ROOT" --no-fund --no-audit
  fi
else
  echo "Skipping npm install because --skip-install was provided."
fi
bash "$REPO_ROOT/scripts/generate-runtime-surfaces.sh"

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

is_interactive() {
  [[ $YES -eq 0 && -t 0 && -t 1 ]]
}

default_answer() {
  local current="$1"
  local fallback="$2"
  if [[ -n "$current" ]]; then
    printf '%s' "$current"
  else
    printf '%s' "$fallback"
  fi
}

ask_yes_no() {
  local prompt="$1"
  local default="$2"
  local current="${3:-}"
  local answer
  local effective_default
  effective_default="$(default_answer "$current" "$default")"

  if ! is_interactive; then
    printf '%s' "$effective_default"
    return
  fi

  local label="y/N"
  if [[ "$effective_default" == "yes" ]]; then
    label="Y/n"
  fi

  read -r -p "$prompt [$label] " answer
  answer="$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')"
  if [[ -z "$answer" ]]; then
    printf '%s' "$effective_default"
    return
  fi
  if [[ "$answer" == "y" || "$answer" == "yes" ]]; then
    printf 'yes'
    return
  fi
  printf 'no'
}

ask_choice() {
  local prompt="$1"
  local default="$2"
  local current="${3:-}"
  shift 3
  local options=("$@")
  local answer
  local effective_default
  local option
  local valid
  effective_default="$(default_answer "$current" "$default")"

  if ! is_interactive; then
    printf '%s' "$effective_default"
    return
  fi

  while true; do
    read -r -p "$prompt [$(IFS=/; echo "${options[*]}") default: $effective_default] " answer
    answer="$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')"
    if [[ -z "$answer" ]]; then
      printf '%s' "$effective_default"
      return
    fi

    valid=0
    for option in "${options[@]}"; do
      if [[ "$answer" == "$option" ]]; then
        valid=1
        break
      fi
    done

    if [[ $valid -eq 1 ]]; then
      printf '%s' "$answer"
      return
    fi

    echo "Invalid choice: $answer" >&2
  done
}

ask_secret() {
  local prompt="$1"
  local existing="${2:-}"
  local answer

  if [[ -n "$existing" || ! is_interactive ]]; then
    printf '%s' "$existing"
    return
  fi

  read -r -s -p "$prompt " answer
  printf '\n' >&2
  printf '%s' "$answer"
}

ensure_profile_source() {
  local env_file="$1"
  local shell_name profile source_line

  shell_name="$(basename "${SHELL:-}")"
  case "$shell_name" in
    zsh) profile="$HOME/.zshrc" ;;
    bash) profile="$HOME/.bashrc" ;;
    *) return 0 ;;
  esac

  source_line="[[ -f \"$env_file\" ]] && source \"$env_file\""

  if [[ -f "$profile" ]] && grep -Fq "$source_line" "$profile"; then
    echo "Shell profile already sources $env_file"
    return 0
  fi

  {
    printf '\n# xgc bootstrap\n'
    printf '%s\n' "$source_line"
  } >>"$profile"

  echo "Updated shell profile: $profile"
}

write_env_file() {
  local env_file="$1"
  local context7_key="$2"
  local exa_key="$3"
  local tavily_key="$4"

  mkdir -p "$(dirname "$env_file")"
  (
    umask 077
    {
      echo "# Generated by scripts/bootstrap-xgc-stack.sh"
      [[ -n "$context7_key" ]] && printf 'export COPILOT_MCP_CONTEXT7_API_KEY=%q\n' "$context7_key"
      [[ -n "$exa_key" ]] && printf 'export COPILOT_MCP_EXA_API_KEY=%q\n' "$exa_key"
      [[ -n "$tavily_key" ]] && printf 'export COPILOT_MCP_TAVILY_API_KEY=%q\n' "$tavily_key"
    } >"$env_file"
  )
  chmod 600 "$env_file"
  echo "Wrote MCP env file: $env_file"
}

clear_env_file() {
  local env_file="$1"
  if [[ -f "$env_file" ]]; then
    rm -f "$env_file"
    echo "Removed MCP env file: $env_file"
  fi
}

install_node_stack() {
  local packages=("$@")
  [[ ${#packages[@]} -eq 0 ]] && return 0
  if ! have_cmd npm; then
    echo "npm is not available. Skipping Node-based LSP installs." >&2
    return 1
  fi
  npm install -g "${packages[@]}"
}

install_go_stack() {
  if ! have_cmd go; then
    echo "go is not available. Skipping gopls install." >&2
    return 1
  fi
  go install golang.org/x/tools/gopls@latest
}

install_rust_stack() {
  if ! have_cmd rustup; then
    echo "rustup is not available. Skipping rust-analyzer install." >&2
    return 1
  fi
  rustup component add rust-analyzer
}

echo "== X for GitHub Copilot bootstrap =="
echo "Upstream OMO MCP inventory: websearch, context7, grep_app"
echo "Upstream OMO LSP candidates selected for Copilot CLI v0: typescript-language-server, vscode-json-language-server, yaml-language-server, bash-language-server, pyright, gopls, rust-analyzer"

ENABLE_CONTEXT7="$(ask_yes_no "Enable Context7 MCP?" "yes" "${XGC_ENABLE_CONTEXT7:-}")"
ENABLE_GREP_APP="$(ask_yes_no "Enable Grep.app MCP?" "yes" "${XGC_ENABLE_GREP_APP:-}")"
WEBSEARCH_PROVIDER="$(ask_choice "Web search provider" "none" "${XGC_WEBSEARCH_PROVIDER:-}" none exa tavily)"

ENABLE_BASE_LSP="$(ask_yes_no "Install and enable the base JS/JSON/YAML/Bash LSP pack?" "yes" "${XGC_ENABLE_BASE_LSP:-}")"
ENABLE_PYRIGHT="$(ask_yes_no "Enable Python LSP (pyright)?" "no" "${XGC_ENABLE_PYRIGHT:-}")"
ENABLE_GOPLS="$(ask_yes_no "Enable Go LSP (gopls)?" "no" "${XGC_ENABLE_GOPLS:-}")"
ENABLE_RUST="$(ask_yes_no "Enable Rust LSP (rust-analyzer)?" "no" "${XGC_ENABLE_RUST:-}")"

AUTO_INSTALL="no"
if [[ $SKIP_INSTALL -eq 0 ]]; then
  AUTO_INSTALL="$(ask_yes_no "Install missing MCP/LSP dependencies automatically when possible?" "yes" "${XGC_AUTO_INSTALL:-}")"
fi

CONTEXT7_KEY=""
if [[ "$ENABLE_CONTEXT7" == "yes" ]]; then
  USE_CONTEXT7_AUTH="$(ask_yes_no "Provide a Context7 API token?" "no" "${XGC_USE_CONTEXT7_AUTH:-}")"
  if [[ "$USE_CONTEXT7_AUTH" == "yes" ]]; then
    CONTEXT7_KEY="$(ask_secret "Context7 API token: " "${COPILOT_MCP_CONTEXT7_API_KEY:-${XGC_CONTEXT7_API_KEY:-}}")"
  fi
fi

EXA_KEY=""
TAVILY_KEY=""
if [[ "$WEBSEARCH_PROVIDER" == "exa" ]]; then
  EXA_KEY="$(ask_secret "Exa API key: " "${COPILOT_MCP_EXA_API_KEY:-${XGC_EXA_API_KEY:-}}")"
  if [[ -z "$EXA_KEY" ]]; then
    echo "No Exa API key provided. websearch will be disabled." >&2
    WEBSEARCH_PROVIDER="none"
  fi
fi

if [[ "$WEBSEARCH_PROVIDER" == "tavily" ]]; then
  TAVILY_KEY="$(ask_secret "Tavily API key: " "${COPILOT_MCP_TAVILY_API_KEY:-${XGC_TAVILY_API_KEY:-}}")"
  if [[ -z "$TAVILY_KEY" ]]; then
    echo "No Tavily API key provided. websearch will be disabled." >&2
    WEBSEARCH_PROVIDER="none"
  fi
fi

NODE_PACKAGES=()
ENABLED_LSP_IDS=()

if [[ "$ENABLE_BASE_LSP" == "yes" ]]; then
  NODE_PACKAGES+=(typescript-language-server typescript vscode-langservers-extracted yaml-language-server bash-language-server)
  ENABLED_LSP_IDS+=(typescript-language-server vscode-json-language-server yaml-language-server bash-language-server)
fi

if [[ "$ENABLE_PYRIGHT" == "yes" ]]; then
  NODE_PACKAGES+=(pyright)
  ENABLED_LSP_IDS+=(pyright)
fi

if [[ "$AUTO_INSTALL" == "yes" ]]; then
  install_node_stack "${NODE_PACKAGES[@]}" || true
  [[ "$ENABLE_GOPLS" == "yes" ]] && install_go_stack || true
  [[ "$ENABLE_RUST" == "yes" ]] && install_rust_stack || true
fi

if [[ "$ENABLE_GOPLS" == "yes" ]]; then
  ENABLED_LSP_IDS+=(gopls)
fi

if [[ "$ENABLE_RUST" == "yes" ]]; then
  ENABLED_LSP_IDS+=(rust-analyzer)
fi

MISSING_LSP_IDS=()
for lsp_id in "${ENABLED_LSP_IDS[@]}"; do
  case "$lsp_id" in
    typescript-language-server)
      have_cmd typescript-language-server || MISSING_LSP_IDS+=("$lsp_id")
      ;;
    vscode-json-language-server)
      have_cmd vscode-json-language-server || MISSING_LSP_IDS+=("$lsp_id")
      ;;
    yaml-language-server)
      have_cmd yaml-language-server || MISSING_LSP_IDS+=("$lsp_id")
      ;;
    bash-language-server)
      have_cmd bash-language-server || MISSING_LSP_IDS+=("$lsp_id")
      ;;
    pyright)
      have_cmd pyright-langserver || MISSING_LSP_IDS+=("$lsp_id")
      ;;
    gopls)
      have_cmd gopls || MISSING_LSP_IDS+=("$lsp_id")
      ;;
    rust-analyzer)
      have_cmd rust-analyzer || MISSING_LSP_IDS+=("$lsp_id")
      ;;
  esac
done

if [[ ${#MISSING_LSP_IDS[@]} -gt 0 ]]; then
  echo "The following selected LSP servers are not currently installed: ${MISSING_LSP_IDS[*]}" >&2
  echo "They will still be written into lsp.json so the setup remains faithful to OMO and can be completed later." >&2
fi

SESSION_ENV_FILE="$REPO_ROOT/.xgc/bootstrap/session-env.sh"
PERSIST_ENV="no"
if [[ -n "$CONTEXT7_KEY" || -n "$EXA_KEY" || -n "$TAVILY_KEY" ]]; then
  PERSIST_ENV="$(ask_yes_no "Persist MCP secrets into ~/.config/xgc/env.sh?" "yes" "${XGC_PERSIST_ENV:-}")"
fi

if [[ "$PERSIST_ENV" == "yes" ]]; then
  ENV_FILE="${XGC_ENV_FILE:-$HOME/.config/xgc/env.sh}"
  write_env_file "$ENV_FILE" "$CONTEXT7_KEY" "$EXA_KEY" "$TAVILY_KEY"
  clear_env_file "$SESSION_ENV_FILE"
  if [[ $SKIP_PROFILE -eq 0 ]]; then
    LINK_PROFILE="$(ask_yes_no "Source that env file from your shell profile?" "yes" "${XGC_LINK_PROFILE:-}")"
    if [[ "$LINK_PROFILE" == "yes" ]]; then
      ensure_profile_source "$ENV_FILE"
    fi
  fi
elif [[ -n "$CONTEXT7_KEY" || -n "$EXA_KEY" || -n "$TAVILY_KEY" ]]; then
  write_env_file "$SESSION_ENV_FILE" "$CONTEXT7_KEY" "$EXA_KEY" "$TAVILY_KEY"
  echo "Secrets were kept repo-local for this workspace only."
  echo "Use scripts/use-xgc-env.sh to run Copilot CLI commands with those MCP keys."
else
  clear_env_file "$SESSION_ENV_FILE"
fi

SPEC_FILE="$(mktemp "$REPO_ROOT/.tmp/bootstrap-spec.XXXXXX")"
trap 'rm -f "$SPEC_FILE"' EXIT

if [[ -n "$CONTEXT7_KEY" ]]; then
  export CONTEXT7_KEY_PRESENT=yes
else
  export CONTEXT7_KEY_PRESENT=no
fi

node --input-type=commonjs - "$SPEC_FILE" "$REPO_ROOT" "$ENABLE_CONTEXT7" "$ENABLE_GREP_APP" "$WEBSEARCH_PROVIDER" "${#ENABLED_LSP_IDS[@]}" "${ENABLED_LSP_IDS[@]}" <<'NODE'
const fs = require("node:fs");

const specPath = process.argv[2];
const repoRoot = process.argv[3];
const enableContext7 = process.argv[4] === "yes";
const enableGrepApp = process.argv[5] === "yes";
const websearchProvider = process.argv[6];
const lspCount = Number(process.argv[7]);
const lspIds = process.argv.slice(8, 8 + lspCount);

const spec = {
  repoRoot,
  mcp: {
    context7: {
      enabled: enableContext7,
      authEnv: process.env.CONTEXT7_KEY_PRESENT === "yes" ? "COPILOT_MCP_CONTEXT7_API_KEY" : null
    },
    grep_app: {
      enabled: enableGrepApp
    },
    websearch: {
      provider: websearchProvider
    }
  },
  lsp: {}
};

for (const lspId of lspIds) {
  spec.lsp[lspId] = true;
}

fs.writeFileSync(specPath, `${JSON.stringify(spec, null, 2)}\n`);
NODE

npm exec --prefix "$REPO_ROOT" -- tsx "$REPO_ROOT/scripts/render-tooling-config.ts" "$SPEC_FILE"

echo "Generated:"
echo "- $REPO_ROOT/.github/mcp.json"
echo "- $REPO_ROOT/lsp.json"
echo "- $REPO_ROOT/.xgc/bootstrap/selected-tooling.json"

bash "$REPO_ROOT/scripts/validate-plugin.sh"

echo "Bootstrap complete."
